name: Notificacion Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificacion a ntfy.sh
        run: |
          curl -d "✅ Nuevo push en el repositorio: ${{ github.repository }} por ${{ github.actor }}" \
               https://ntfy.sh/devops-itla
